version: '2.5'
services:
  skycalendarapp:
    build: 
      context: .
      dockerfile: Dockerfile
    image: front-hackaton
    container_name: front-hackaton
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "7575:80"